### ISSUE TITLE
CK Editor

### ISSUE THREAD

**Issue by laxap** [laxap/bsdist#3]
--- moved from forge.typo3.org, orig from: 2017-05-05 ---

Problem with Page ts with the new rte editor CKEditor.
In default configuration. It's not possible to set a link !
Using TYPO3 8.7.1

**Comment by ewokhias** [comment]
It's not just setting links that doesn't work. In a newly setup TYPO3 8.7.1 installation, following buttons won't work: 
- bold
- italic
- sub-/superscript
- lists
- quotes
- links

Nevertheless, thank you very much for this great distribution.

**Comment by laxap** [comment]
I know. I have a working config from another project and will try to integrate it as soon as possible.

Regards, Pascal

**Comment by laxap** [comment]
Version 2.0.2 uses the default ckeditor configuration.
